name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual workflow execution'

env:
  PYTHON_VERSION: '3.11'

jobs:
  manual-trigger:
    name: Manual Workflow Trigger
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install email-validator
        pip install opentelemetry-api opentelemetry-sdk
        pip install -r requirements.txt
    
    - name: Run platform validation
      run: |
        echo "🎯 Manual workflow trigger: ${{ github.event.inputs.reason }}"
        python scripts/validate_platform.py
    
    - name: Run basic tests
      run: |
        python -m pytest tests/test_basic.py -v
    
    - name: Workflow completion
      run: |
        echo "✅ Manual workflow completed successfully!"
        echo "Trigger reason: ${{ github.event.inputs.reason }}"
        echo "Platform is operational and ready for deployment."
